- name: Include serverroles dynamically
  hosts: all
  become: yes
  tasks:
    - include_role:
        name: serverroles
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version('24.04', '==')

